@HostAddress = http://localhost:5290
@Path = {{HostAddress}}/number-to-words

# Will convert a number to words
GET {{Path}}/123
// Result: ONE-HUNDRED AND TWENTY-THREE

###

# Will return a negative number
GET {{Path}}/-789
// Result: NEGATIVE SEVEN-HUNDRED AND EIGHTY-NINE

###

# Will return an error for non-numbers
GET {{Path}}/abc

###
